- README.adoc
- src/main/java/org/mule/tools/mule/ApiException.java
- src/main/java/org/mule/tools/mule/agent/AgentApi.java
**Fix README typo:** - d6e89fc5c638e188d4c4793c5df3881fbacb158d
Some of the pom examples are missing a `l` in their groupid for the value `org.mule.tools`
**Provide uri when agent api request fails:** - c294532625089c98e2871235b91a003d50cb8399
When an API request to the agent api fails a user receives:
```
[ERROR] Failure: 405 HTTP method PUT is not supported by this URL:
```
This commit demonstrates a exception returned that contains the uri. This way the user has better context on why the api call failed.
```
[ERROR] Failure: 405 HTTP method PUT is not supported by this URL: http://52.25.43.249:9999/breakit/mule/applications/maven-project-beep
```
> Fix README typo and provide uri used when agent api request fails

- src/main/java/org/mule/tools/maven/plugin/mule/DeployMojo.java
- src/main/java/org/mule/tools/maven/plugin/mule/cloudhub/CloudhubApi.java
The fix prevents the properties attribute from being included in the json, that is sent to Cloudhub, when the properties are not specified as a parameter for the deploy.
> EE-4692: Fix for ch deploy deletes all properties

- pom.xml
When upgrading the code to build on Java8, the javadoc tool on this version introduce the doclint feature that performs validations under the javadoc comments. This cause the build to fail when doing the release. By setting this property, we are disabling the validations.
> MMP-119 Update javadoc plugin to work on Java8

- src/main/java/org/mule/tools/maven/mojo/AbstractMuleMojo.java
- src/main/java/org/mule/tools/maven/mojo/GenerateSourcesMojo.java
- src/main/java/org/mule/tools/maven/mojo/GenerateTestSourcesMojo.java
- src/main/java/org/mule/tools/maven/mojo/InitializeMojo.java
- src/main/java/org/mule/tools/maven/mojo/PackageMojo.java
- src/main/java/org/mule/tools/maven/mojo/ProcessSourcesMojo.java
- src/main/java/org/mule/tools/maven/mojo/ValidateMojo.java
- src/main/java/org/mule/tools/maven/repository/RepositoryGenerator.java
- src/main/java/org/mule/tools/maven/util/FileUtils.java
- src/test/java/org/mule/tools/maven/mojo/InitializeMojoTest.java
- src/test/java/org/mule/tools/maven/mojo/ValidateMojoTest.java
- src/test/java/org/mule/tools/maven/repository/RepositoryGeneratorTest.java
I changed the tests to avoid validate mojo execution using the log, that is error prone and something the log can contains dynamic information.
I have included a utility class to mark and check read only flag, because in windows the File#setReadOnly does not work properly.
> Fixing tests to work on windows and adding skipValidation flag

- mule-artifact-it/mule-deployer-it/pom.xml
- mule-artifact-it/mule-deployer-it/src/test/java/integrationTests/mojo/SettingsConfigurator.java
- mule-artifact-it/mule-packager-it/pom.xml
- mule-artifact-it/mule-packager-it/src/test/java/integrationTests/mojo/SettingsConfigurator.java
- mule-artifact-it/pom.xml
- mule-classloader-model/pom.xml
- mule-deployer/pom.xml
- mule-maven-plugin/pom.xml
- pom.xml
-Rename modules to display correctly on reports
-IT will report code coverage
-Get value of skipTests and pass it to maven-dependency-plugin, that way if you skip tests, the standalone won't be downloaded.
> Include IT to report coverage and update some modules names for the report

- pom.xml
- Line ending formatter validation fails in windows because of Git's
core.autocrlf property set to true by default, changing all the LRs to
CRLFs at checkout
> MULE-15562: Fix Mule-4-Status-Windows pipeline

- mule-deployer/src/main/java/org/mule/tools/client/AbstractMuleClient.java
- mule-deployer/src/main/java/org/mule/tools/client/authentication/model/AnypointCredential.java
- mule-deployer/src/main/java/org/mule/tools/client/authentication/model/AnypointToken.java
- mule-deployer/src/main/java/org/mule/tools/client/authentication/model/CredentialType.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/AnypointDeployment.java
- mule-deployer/src/test/java/org/mule/tools/client/arm/ArmClientWithTokenTestCase.java
This PR adds a configuration to use Pre-Authenticated Bearer Token for authentication against the platform.
There is no change to authentication using username and password.
To use bearer token instead of username and password, either set a system property `anypoint.authToken` or add `<authToken>{token value}</authToken>` to the xml element, similar to username/password approach.
When bearer token is used, the plugin will use it as is for any operations against the anypoint platform apis. In case of invalid token, plugin throws unauthorized access error.
> Adds configuration to use Bearer Token for authentication

- mule-deployer/src/main/java/org/mule/tools/client/AbstractMuleClient.java
- mule-deployer/src/main/java/org/mule/tools/client/authentication/AuthenticationServiceClient.java
- mule-deployer/src/test/java/org/mule/tools/client/AbstractMuleClientTestCase.java
This PR adds `x-anypoint-session-extend` header to base request builder. This will extend the user token expiration value.
> Set token extension header flag

- mule-deployer/src/main/java/org/mule/tools/verification/DefaultDeploymentVerification.java
- mule-deployer/src/main/java/org/mule/tools/verification/fabric/RuntimeFabricDeploymentVerification.java
- mule-deployer/src/test/java/org/mule/tools/verification/cloudhub/CloudHubDeploymentVerificationTest.java
- mule-deployer/src/test/java/org/mule/tools/verification/fabric/RuntimeFabricDeploymentVerificationTest.java
Original fix by julianpascualMuleSoft
MMP-511 Update error message when deploy validation fail with time out
MMP-511 Don't change app status on RTF deploy verification timeout (#329)
Co-authored-by: julianpascualMuleSoft <julian.pascual@mulesoft.com>
> Backported MMP-511 fixes to the 2.x branch.

- mule-deployer/src/main/java/org/mule/tools/deployment/AbstractDeployerFactory.java
Message thrown by AbstractDeployerFactory is confusing.
We got a "Deployment not supported: ArmDeployment" 
```15:17:16.318 [P=227711:O=0:CT] INFO  c.r.e.w.d.d.DeploybotRequest - [INFO] ------------------------------------------------------------------------
15:17:16.320 [P=227711:O=0:CT] INFO  c.r.e.w.d.d.DeploybotRequest - [ERROR] Failed to execute goal org.mule.tools.maven:mule-maven-plugin:2.3.3:undeploy (default-cli) on project mule-delete: Execution default-cli of goal org.mule.tools.maven:mule-maven-plugin:2.3.3:undeploy failed: Deployment not supported: ArmDeployment -> [Help 1]
15:17:16.320 [P=227711:O=0:CT] INFO  c.r.e.w.d.d.DeploybotRequest - [ERROR] 
```
but origin cause was the missing <packaging>mule</packaging> the the pom.xml.
> Show correct error message corresponding to switch.

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/PackageMojo.java
When packaging a policy, the yaml file must be attached to the maven lifecycle in order to deploy it too.
> MMP-509 Attach policy yaml on maven lifecycle

- mule-deployer/src/main/java/org/mule/tools/verification/cloudhub/CloudHubDeploymentVerification.java
We don't have to stop the application if the deployment fails. If it is the first deploy we don't have to stop the app because it was never deployed. On the other hand, if we are doing a redeploy we should not stop it to respect the "zero downtime updates" policy (that is respected by ui and by cloudhub api): https://docs.mulesoft.com/runtime-manager/managing-applications-on-cloudhub#zero-downtime-updates-with-cloudhub
> SE-17223:Maven Stops a Previous App Instance  if the Re-deployment Fails

- mule-deployer/src/main/java/org/mule/tools/client/core/AbstractClient.java
According to [MMP-545](https://www.mulesoft.org/jira/browse/MMP-545), the POST request uploading the jar files to the platform was not being streamed. POST request were using the multipart/form-data Content-Type with the jar files.
Looking into the Jersey library, there is an option named REQUEST_ENTITY_PROCESSING that when set to "CHUNKED" it divides the data in chunks to upload. Now, when creating the Invocation.Builder at the AbstractClient, this property (and its default chunk size) is set so we now stream data by chunks.
> Fix MMP-545

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/deploy/AbstractMuleDeployerMojo.java
After the addition of the exchange plugin to MMP( https://github.com/mulesoft/mule-maven-plugin/commit/0479f13cf91c3f75bf133101e1975aa0457c17d9 ), the error message that
is shown when there is no configuration to do MuleDeploy is not the
same. Instead of showing "No deployment configuration was defined" it's
showing a NPE. This commit fix that.
> MMP-553:Review Exchange Plugin integration

- mule-deployer/src/main/java/org/mule/tools/deployment/fabric/RequestBuilder.java
- mule-deployer/src/main/java/org/mule/tools/verification/fabric/RuntimeFabricDeploymentVerification.java
- mule-deployer/src/test/java/org/mule/tools/verification/fabric/RuntimeFabricDeploymentVerificationTest.java
We were not filtering by target when checking the deploy.
Previous behaviour:
When having two apps with the same name in two different RTFs, the verificator could verify the wrong one.
Current behaviour:
With the filter by target added to the verificator we ensure that the deployment that is being verified is taken from the right rtf.
> SE-20120: MMP chooses 1st deployment of several with same name during RTF deployment 

- pom.xml
Setting the version prevents showing several warnings like the following one at the start of the building and makes it more stable and predictable.
```
$ mvn clean package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.mule.tools.maven:mule-packager:jar:3.5.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ org.mule.tools.maven:mule-artifact-tools:3.5.2-SNAPSHOT, /Users/mdaloia/dev/projects/mule-maven-plugin/pom.xml, line 467, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.mule.tools.maven:mule-classloader-model:jar:3.5.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for …
```
> Set maven-jar-plugin version

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
The previous version (3.6.1) does not currently exists. At the time of writing this the latest version is 3.1.0 on Maven Central.
> MMP-567: Fix wrong maven-clean-plugin version for Mule Lifecycle

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/CloudHubDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub-project/mule-artifact.json
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
Removing suffix for deployments because Ch always uses the last patch
for the version (if a suffix is specified it fails). For redeploys we do
nothing because you can deploy to the patch that is already running. I am updating the versions to the ones available in the cloudhub testing account currently and adding a SNAPSHOT suffix to test this fix.
> SE-20302:CloudHub Deployment Fails with Error 400 Bad Request

- build.jenkinsfile
in order to deploy 3.5.3-SNAPSHOT to the internal repo
> add support/3.5.x to protected branches

- mule-packager/src/main/java/org/mule/tools/api/repository/ArtifactInstaller.java
- mule-packager/src/test/java/org/mule/tools/api/repository/ArtifactInstallerTest.java
The artifact installer is assuming that every dependency has a pom file.
This is not the case for the tools.jar that is obtained from the jre.
This fix consists of checking that the pom exists before trying to copy
it to target folder.
> SE-21008:Maven Plugin: Failing to build application from command line

- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/InstallMojoTest.java
- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/MojoTest.java
- mule-extension-model-loader/pom.xml
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CompileMojo.java
- mule-packager/pom.xml
- pom.xml
We need EE dependencies to obtain the ext-models of the mule plugins for
the AST. But the MMP should not need the EE repos configured to be used.
So, these new dependencies are packaged in a
mule-extension-model-loader-dependencies.jar. When mmp is used this jar
is uncompressed and the inner jars are added to the classpath
> MMP-586: Package EE dependencies when building MMP

- mule-packager/src/main/java/org/mule/tools/api/util/ArtifactUtils.java
- mule-packager/src/main/java/org/mule/tools/api/util/DependencyProject.java
- mule-packager/src/main/java/org/mule/tools/api/util/Project.java
- mule-packager/src/main/java/org/mule/tools/api/util/SourcesProcessor.java
- mule-packager/src/main/java/org/mule/tools/api/validation/project/DomainBundleProjectValidator.java
- mule-packager/src/main/java/org/mule/tools/api/validation/project/MuleProjectValidator.java
- mule-packager/src/main/java/org/mule/tools/api/validation/resolver/model/DependenciesFilter.java
- mule-packager/src/test/java/org/mule/tools/api/validation/project/DomainBundleProjectValidatorTest.java
- mule-packager/src/test/java/org/mule/tools/api/validation/resolver/MulePluginResolverTest.java
- mule-packager/src/test/java/org/mule/tools/api/validation/resolver/model/DependenciesFilterTest.java
- mule-packager/src/test/java/util/ResolverTestHelper.java
Using getArtifacts instead of getDependencies because returns all dependencies including the transitive ones.
https://maven.apache.org/ref/3.2.3/apidocs/org/apache/maven/project/MavenProject.html#getArtifacts()
> [SE-23105][W-10624135] - Mule Maven Plugin not finding Transitive Dependencies for Shared Libraries

- mule-extension-model-loader/pom.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/internal/DefaultExtensionModelLoader.java
In order to remove tooling-client dep, I added manually the ext models that were not added. Now, it's the same that introspection service : https://github.com/mulesoft/mule-ang-introspection-service/blob/9636fd82f993c6076220fd1a93926469c1268f2c/introspector/src/main/java/com/mulesoft/runtime/ang/introspector/extension/DefaultExtensionModelLoader.java#L44
> W-10877491: Remove remaining deps that are not in the public repo from the extension-model-loader

- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/test/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployerTest.java
We are getting the default value for object store from the property
objectStoreV1Enabled given by this endpoint
https://anypoint.mulesoft.com/cloudhub/api/buildinfo/environment
That is always true for CH, we need to extract this value from the runtime version
> W-11025088: Objectstore error while deploying application to cloudhub using Maven

- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/InstallMojoTest.java
- mule-artifact-it/mule-packager-it/src/test/resources/incomplete-mule-plugin/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/incomplete-mule-plugin/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/incomplete-mule-plugin/src/main/mule/simple-lib.xml
- mule-artifact-it/mule-packager-it/src/test/resources/incomplete-mule-plugin/src/test/resources/log4j2-test.xml
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CompileMojo.java
…ule (#573)
Imported global configurations and error handlers from a Mule library
style plugins broken with Mule Maven Plugin 3.6.0+
We should avoid ast validation for app that are packaged as
mule-plugins. Because those apps can be incomplete and only work when
they are used in a specific context
> cherrypick W-11119054

- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/pom.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CompileMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/CompileMojoTest.java
we should move the AST generation to the process-classes phase. Generating it after compile phase will allow us to have all the dependencies resolved (including transitive ones and those with "provided" or "runtime" scope). Also if the app is already compiled we can avoid the temporary app for obtaining the extension models. 
According to maven, process-classes phase is meant for:  
`post-process the generated files from compilation, for example to do bytecode enhancement on Java classes`
I think this is the right phase to do this if we see AST generation as a post process that takes the compiled resources and uses them to generate an enhanced representation of the app.
> W-11286314:AST generation fails when having deps with provided scope

- mule-artifact-it/mule-packager-it/src/test/resources/simple-lib/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/simple-lib/src/main/mule/simple-lib.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
when certain exception types selected in Error Handler.
Root cause:Mule apikit classes were present in the classloader when http-connector extension model was resolved.A dependency conflict was preventing MMP to obtain all the error-types in the model. In runtime, each connector
has its own classloader.
Solution: add the jars of the plugins to the classloader (this is needed to get the files to validate AST) AFTER the resolution of all the extension models
> W-11369839:Mule Maven Plugin AST Generation failing

- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/InstallMojoTest.java
- mule-artifact-it/mule-packager-it/src/test/resources/test-child/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/test-child/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/test-child/src/main/mule/test-lib-project.xml
- mule-artifact-it/mule-packager-it/src/test/resources/test-parent-pom/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/test-parent-pom/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/test-relative-path/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/test-relative-path/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/test-relative-path/src/main/mule/test-child-api-project.xml
- mule-artifact-it/mule-packager-it/src/test/resources/test-relative-path/src/main/resources/application-types.xml
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/AbstractMuleMojo.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/ContentGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/ContentGeneratorFactory.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/DomainBundleContentGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/MuleContentGenerator.java
- mule-packager/src/test/java/org/mule/tools/api/ContentGeneratorTest.java
* W-11327063: Packaging not working properly having...
a mule-lib that uses a parent pom that is referenced using a parent's
property as version.
The pom generated by maven-jar-plugin in the same scenario has the
version copied from the parent when it's installed. We need to do this
for relativepath cases.
* removing commas
> Cherrypick W-11327063

- mule-artifact-it/mule-packager-it/src/test/resources/simple-lib/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/simple-lib/src/main/mule/simple-lib.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
when certain exception types selected in Error Handler.
Root cause:Mule apikit classes were present in the classloader when
http-connector extension model was resolved. In runtime, each connector
has its own classloader.
Solution: add the jars of the plugins to the classloader (this is needed to get the files to validate AST) AFTER the resolution of all the extension models
> W-11369839:Mule Maven Plugin AST Generation failing (#604)

- integrationTests-Windows.jenkinsfile
because w7 is not available anymore in jenkins
> W-11727183:Updating windows agent (cherrypick)

- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/src/main/mule/simple-app-with-lib.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-extension-model-loader/src/test/java/org/mule/tooling/internal/AstGeneratorTest.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
It was failing because a different version of a connector was being resolved transitively. So, now the extension models of the direct dependencies are resolved first
> W-11369839:Mule Maven Plugin AST Generation failing when certain exception types selected in Error Handler

- mule-deployer/src/main/java/org/mule/tools/model/Deployment.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/PackageMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/DomainBundleLifecycleMapping.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/LifecyclePluginsGAVs.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/MuleArtifactContentResolver.java
…y mule-maven-plugin (#636)
* W-11771239: Update Maven plugin versions on Mule lifecycles
Updated the Apache Maven plugins versions defined to be used on the Mule lifecycle in order to prevent usage/inclusion of `plexus-utils` older than 3.0.16 which are impacted by CVE-2017-1000487.
* Set project main file as expected by maven-install-plugin
Newer versions of `maven-install-plugin` validates that a project main file is set [1], otherwise it fails with a message saying that no main file was assigned to the project but it has other attached files [2].
[1]: https://github.com/apache/maven-install-plugin/blob/9f77fb95ab2a95b1d8d0c34c39c6f088f9f690ab/src/main/java/org/apache/maven/plugins/install/InstallMojo.java#L200-L201 [2]: https://github.com/apache/maven-install-plugin/blob/9f77fb95ab2a95 …
> Cherrypick w 11771239

- mule-deployer/src/main/java/org/mule/tools/client/cloudhub/model/Application.java
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/CloudHubDeployment.java
- mule-deployer/src/test/java/org/mule/tools/model/anypoint/CloudHubDeploymentTest.java
Based on this [entry](https://help.mulesoft.com/s/ideas#08734000000HV2fAAG) from the ideas portal.
The idea is to add a way to handle the _loggingCustomLog4JEnabled_ property when deploying an application to CloudHub, which, at the moment, can only be done by following [this article](https://help.mulesoft.com/s/article/How-to-disable-CloudHub-logging-using-API)
> W-11524895: Disable default CloudHub log4j2 settings when deploying applications

- mule-deployer/src/main/java/org/mule/tools/client/cloudhub/model/Application.java
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/CloudHubDeployment.java
- mule-deployer/src/test/java/org/mule/tools/model/anypoint/CloudHubDeploymentTest.java
: Disable default CloudHub log4j2 settings when deploying applications (#607)
* Added loggingCustomLog4JEnabled field to API call when deploying to CloudHub
* Changed 'loggingCustomLog4JEnabled' property name used in cloudHubDeployment to 'disableCloudHubLogs'
Co-authored-by: egrave <eduardograve3@gmail.com>
> CP: W-11524895

- mule-extension-model-loader/src/test/java/org/mule/tooling/internal/ExtensionModelLoaderTest.java
DSL won't be included in runtime 4.5.0 GA. That extesion model was removed and that is why the test is failing
> Test fixed that was broken since w-11996025

- mule-extension-model-loader/pom.xml
Changes made:
- Added mule-module-spring-config dependency to mule-extension-model-loader/pom.xml
> W-12558941: Applications that depend on mule-module-spring-config can't be packaged

- mule-packager/pom.xml
- mule-packager/src/main/java/org/mule/tools/api/verifier/policy/PolicyYamlVerifier.java
- mule-packager/src/test/java/org/mule/tools/api/verifier/ProjectVerifierFactoryTest.java
- mule-packager/src/test/resources/org/mule/tools/api/verifier/custom.policy.test.yaml
- pom.xml
In October of 2022, a [critical flaw](https://nvd.nist.gov/vuln/detail/CVE-2022-1471) was found in the SnakeYAML package, which allowed an attacker to benefit from remote code execution by sending malicious YAML content and this content being deserialized by the constructor. Finally, in February 2023, the SnakeYAML 2.0 release was pushed that resolves this flaw, also referred to as [CVE-2022-1471](https://nvd.nist.gov/vuln/detail/CVE-2022-1471). Let’s break down how this version can help you resolve this critical flaw.
> W-12354025: Upgrade to snakeyaml 2.0 to address vulnerability in earrlier  versions

- .github/CODEOWNERS
- CODEOWNERS
This PR updates the CODEOWNERS file in the new mandatory format required at Salesforce. You can find more information here: https://salesforce.quip.com/tJgIAMHf1eYH
> W-13705272 | Updating CODEOWNERS file to follow new mandatory format

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/LifecyclePluginsGAVs.java
- pom.xml
Updated dependency to exchange-mule-maven-plugin version:0.0.20 to fix vulnerability CVE-2021-26291
- Task
- [W-13830473](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001X2u4yYAB/view)
> W-13830473: fixed CVE-2021-26291 vulnerability due to exchange-mule-maven-plugin version 0.0.17

- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/ProcessClassesMojoTest.java
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-plugin-with-unresolved-properties/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-plugin-with-unresolved-properties/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-plugin-with-unresolved-properties/src/main/mule/mule-application-plugin-with-unresolved-properties.xml
- mule-artifact-it/mule-packager-it/src/test/resources/test-relative-path/pom.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-extension-model-loader/src/test/java/org/mule/tooling/internal/MavenClientTest.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
- pom.xml
[W-14998627](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001jkagJYAQ/view)
When building with MMP and having a project that is considered an application (see asApplication) and is also a mule-plugin (see Classifier), the final application will set some variables when using this plugin.
Therefore no error should be caught when building with MMP.
An integration test was implemented that reproduces the Bug issue.
New bug for Runtime, to implement fix: [W-15556985](https://gus.lightning.force.com/a07EE00001pKJUKYA4)
New user.story for MMP to remove temporary MMP fix when Runtime fix is implemented: [W-15554719](https://gus.lightning.force.com/a07EE00001pJKzwYAG)
Integrations test error before implementing MMP fix with if-else cause:
Final Build :
> W-14998627: Mule Application plugin with unresolved property should not fail

- integrationTests-Windows.jenkinsfile
- integrationTests.jenkinsfile
- integrationTestsJDK11.jenkinsfile
Update maven default version to "Maven-3.9.4", so that integration tests at Jenkins run ok
Updating the maven version, it started to run successfully:
> W-17089835: update maven default value in another jenkins files
