mulesoft/mule-maven-plugin

- src/main/java/org/mule/tools/maven/mojo/model/lifecycle/MuleLifecycleMapping.java
…ing compatible with the 3.3.9 implementation, to fall back to the 3.3.3 implementation
> Support for Maven 3.5.x

- src/main/java/org/mule/tools/api/packager/ContentGenerator.java
- src/main/java/org/mule/tools/api/packager/FolderNames.java
- src/main/java/org/mule/tools/api/packager/ProjectFoldersGenerator.java
- src/main/java/org/mule/tools/api/packager/Validator.java
- src/main/java/org/mule/tools/api/packager/exception/ValidationException.java
- src/main/java/org/mule/tools/artifact/archiver/internal/MuleArchiver.java
- src/main/java/org/mule/tools/artifact/archiver/internal/PackageBuilder.java
- src/main/java/org/mule/tools/maven/mojo/AbstractMuleDeployerMojo.java
- src/main/java/org/mule/tools/maven/mojo/DeployMojo.java
- src/main/java/org/mule/tools/maven/mojo/GenerateSourcesMojo.java
- src/main/java/org/mule/tools/maven/mojo/GenerateTestSourcesMojo.java
- src/main/java/org/mule/tools/maven/mojo/InitializeMojo.java
- src/main/java/org/mule/tools/maven/mojo/ValidateMojo.java
- src/main/java/org/mule/tools/maven/mojo/model/ArtifactDescription.java
- src/main/java/org/mule/tools/maven/mojo/model/DeploymentConfiguration.java
- src/main/java/org/mule/tools/maven/mojo/model/PackagingType.java
- src/test/java/integrationTests/mojo/MojoTest.java
- src/test/java/integrationTests/mojo/ValidateMojoTest.java
- src/test/java/org/mule/tools/api/packager/ContentGeneratorTest.java
- src/test/java/org/mule/tools/api/packager/PackagerTestUtils.java
- src/test/java/org/mule/tools/api/packager/ProjectFoldersGeneratorTest.java
- src/test/java/org/mule/tools/api/packager/ValidatorTest.java
- src/test/java/org/mule/tools/artifact/archiver/internal/MuleArchiverTest.java
- src/test/java/org/mule/tools/artifact/archiver/internal/PackageBuilderTest.java
- src/test/java/org/mule/tools/maven/mojo/AbstractMuleMojoTest.java
- src/test/java/org/mule/tools/maven/mojo/GenerateSourcesMojoTest.java
- src/test/java/org/mule/tools/maven/mojo/GenerateTestSourcesMojoTest.java
- src/test/java/org/mule/tools/maven/mojo/InitializeMojoTest.java
- src/test/java/org/mule/tools/maven/mojo/PackageMojoTest.java
- src/test/java/org/mule/tools/maven/mojo/ValidateMojoTest.java
MMP-154, refactor initializeMojo
MMP-154,add thest for projectfoldersGenerator
MMP-154, final refactor and test for contentGenerator. Move classes to api package and minor fix on validations
MMP-154, change api to work with paths
MMP-154,remove usless class
MMP-154, minor refactor, remove unnecessary code, and improve tests
> MMP-154, refactor validationMojo and create a java agnostic API

- mule-maven-plugin/.gitignore
- mule-maven-plugin/pom.xml
has Mule Core deps so there is a circular dep there that we would need
to fix
> MULE-13651: Mule Packager is a lib which goes inside the distro but it

- mule-artifact-it/pom.xml
- pom.xml
Add property to disable IT on build. That way during the build/check stage on the new pipeline, the IT won't run.
> MMP-297 Add property to skip IT on build

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/AbstractGenericMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/GenerateTestResourcesMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessResourcesMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/TestCompileMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/version/LifecycleMappingMavenVersionless.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/utils/ProjectDirectoryUpdater.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/AbstractMuleMojoTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/CompileMojoTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/GenerateSourcesMojoTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/GenerateTestResourcesMojoTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/GenerateTestSourcesMojoTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/ProcessSourcesMojoTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/TestCompileMojoTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/model/lifecycle/MuleLifecycleMappingMavenVersionlessTest.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/utils/ProjectDirectoryUpdaterTest.java
- mule-packager/src/main/java/org/mule/tools/api/packager/structure/FolderNames.java
MMP-324, add tests for PorjectDirectoryUpdater
MMP-324, add some more mojos to wire things properly, add test remove un used imports
> MMP-324, modify liecycle wire and projec build directory update

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CleanMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/SiteMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/model/lifecycle/MuleLifecycleMappingMavenVersionlessTest.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/MuleContentGenerator.java
MMP-327, wire clean and site mojos so redirection by projectBuildDirectory works properly
> MMP-327, exclude project build directory gen generating mule-src

- mule-packager/src/main/java/org/mule/tools/api/packager/sources/DefaultValuesMuleArtifactJsonGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/MuleArtifactContentResolver.java
(cherry picked from commit 0ba7532)
> MMP-407: packages should be exported with dot separator, not slash

- mule-deployer/src/main/java/org/mule/tools/client/standalone/controller/Controller.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/DefaultValuesMuleArtifactJsonGenerator.java
- pom.xml
This depends on https://github.com/mulesoft/mule-api/pull/516
> MULE-15637: Custom log file in Mule 4

- mule-deployer/src/main/java/org/mule/tools/client/fabric/model/ApplicationModify.java
- mule-deployer/src/main/java/org/mule/tools/client/fabric/model/ApplicationRequest.java
- mule-deployer/src/main/java/org/mule/tools/client/fabric/model/DeploymentRequest.java
- mule-deployer/src/main/java/org/mule/tools/deployment/AbstractDeployerFactory.java
- mule-deployer/src/main/java/org/mule/tools/deployment/fabric/RequestBuilder.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/AnypointDeployment.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/ArmDeployment.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/CloudHubDeployment.java
- mule-deployer/src/main/java/org/mule/tools/validation/DeploymentValidatorFactory.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/AbstractGenericMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/deploy/AbstractMuleDeployerMojo.java
Also included the support for properties on the RF deploy.
> Fix deployment to RF for mule 3 apps

- mule-deployer/src/main/java/org/mule/tools/client/cloudhub/model/Application.java
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/CloudHubDeployment.java
- mule-deployer/src/main/java/org/mule/tools/verification/cloudhub/CloudHubDeploymentVerification.java
- mule-deployer/src/test/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployerTest.java
- mule-deployer/src/test/java/org/mule/tools/verification/cloudhub/CloudHubDeploymentVerificationTest.java
- SE-9491 mule-maven-plugin removes the application properties during redeployment
> MMP-451 Check correct status when redeploying app to CH

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:resolve-plugins (resolve-plugins) on project bug-xmlmodule-fails: Could not find artifact org.apache.maven.plugins:maven-site-plugin:jar:3.6.1 in centralMirror
> maven-site-plugin:3.8.2

- src/main/java/org/mule/tools/maven/plugin/mule/ClusterConfigurator.java
- Fixing issue while generating mule-cluster.properties file
> EE-7112: Review DataWeaveClusterAppTestCase

- integrationTestsJDK11.jenkinsfile
- mule-deployer/pom.xml
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- pom.xml
* SE-8863 Validate deployment worker values before set default ones (#232)
* MMP-520 Fix deployment issue when running on openJDK11
> MMP-520 Fix deployment issue when running on openJDK11 (#346)

- mule-deployer/src/main/java/org/mule/tools/client/AbstractMuleClient.java
- mule-deployer/src/main/java/org/mule/tools/client/arm/model/User.java
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/test/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployerTest.java
* Added support for client token deployment
* Fixed Cloudhub application config.
> Added support for client token deployment - CP 3.x (#368)

- mule-maven-plugin/src/main/java/org/mule/tools/maven/config/proxy/ProxyConfiguration.java
And add proxyHost and proxyPort properties.
> MMP-533 Avoid throwing error if proxy credentials are not set

- src/main/java/org/mule/tools/maven/plugin/mule/proxy/ProxyConfiguration.java
And add proxyHost and proxyPort properties.
> [2.x] MMP-533 Avoid throwing error if proxy credentials are not set

- renovate.json
Original PR was closed, recreate it.
> Configure Renovate manually

- mule-packager/pom.xml
- mule-packager/src/main/java/org/mule/tools/api/util/MavenProjectInformation.java
- mule-packager/src/main/java/org/mule/tools/api/validation/exchange/ExchangeRepositoryMetadata.java
Adding exchange utils dependency in order to extract exchange logic and validations
> [EXC-6152] Adding exchange utils dependency, extracting Exchange logic

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
Add validation mojo to verify step
> [EXC-6430] Validation mojo

- build.jenkinsfile
Addling list of protected branches
> sod: adding protected branch validation

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
- pom.xml
Bump exchange-mule-maven to 0.0.12
> Bump exchange-mule-maven-plugin to 0.0.12

- mule-deployer/src/main/java/org/mule/tools/verification/cloudhub/CloudHubDeploymentVerification.java
if the Re-deployment Fails. Cherrypick
Co-authored-by: erecofsky <erecofsky@hotmail.com>
> se-17223:Maven Stops a Previous App Instance (#444)

- MMP-Release.jenkinsfile
the release plugin is failing due to protected branches
> Update release jenkinsfile

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
- pom.xml
@egrave This bump fixes the altDeploymentRepository usecase.
Just FYI
> [EXC-7088] Bump exchange-mule-maven to 0.0.13

- mule-packager/src/main/java/org/mule/tools/api/packager/sources/DefaultValuesMuleArtifactJsonGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/MuleArtifactContentResolver.java
- mule-packager/src/main/java/org/mule/tools/api/util/XmlFactoryUtils.java
- mule-packager/src/test/java/org/mule/tools/api/util/XmlFactoryUtilsTest.java
Set features to. the sax factory to prevent xxe attack.
[MMP-557](https://www.mulesoft.org/jira/browse/MMP-557)
> MMP-557: prevent xxe attack

- mule-packager/src/main/java/org/mule/tools/api/packager/sources/DefaultValuesMuleArtifactJsonGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/MuleArtifactContentResolver.java
- mule-packager/src/main/java/org/mule/tools/api/util/XmlFactoryUtils.java
- mule-packager/src/test/java/org/mule/tools/api/util/XmlFactoryUtilsTest.java
> MMP-557: prevent xxe attack (#463)

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
- pom.xml
Cherry picking changes done in `support/3.5.x` with PR #485, #486 and #487 to `support/3.x`
> Cherry picking PR #485, #486 and #487 changes into `support/3.x`

- mule-packager/src/main/java/org/mule/tools/api/classloader/model/ApplicationClassLoaderModelAssembler.java
- mule-packager/src/main/java/org/mule/tools/api/classloader/model/util/ArtifactUtils.java
- mule-packager/src/main/java/org/mule/tools/api/repository/RepositoryGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/util/SourcesProcessor.java
- mule-packager/src/test/java/org/mule/tools/api/classloader/model/ApplicationClassLoaderModelAssemblerTest.java
- mule-packager/src/test/java/org/mule/tools/api/repository/RepositoryGeneratorTest.java
There was no support for maven profiles. The support is added in runtime
and munit already. This commit complements the fix adding support for
profiles in the mule packager
> SE-17938: App packaged with maven profile doesn't run.Cannot load class

- mule-extension-model-loader/pom.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/internal/DefaultExtensionModelService.java
> MMP-592: "A schema cannot contain two global components with the same

- mule-extension-model-loader/pom.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/ConfigurationException.java
- mule-extension-model-loader/src/test/java/org/mule/tooling/internal/AstGeneratorTest.java
- mule-extension-model-loader/src/test/resources/test-project/src/main/mule/mule-config2.xml
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CompileMojo.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/CompileMojoTest.java
- pom.xml
MMP-579:Add AST validations to MMP
MMP-594:Packager fails when running without `clean` goal
> MMP-579, MMP-594

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CompileMojo.java
There was an error when using projectBuildDirectory maven parameter
> MMP-595:Failed to execute goal compile when running MUnit Test Suite

- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/src/main/mule/simple-app-with-lib.xml
- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/src/main/resources/dataweave/set-empty-payload.dwl
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CompileMojo.java
I am also adding a flag to optionally disable AST validation to avoid this kind of problems in the future
> W-10957568:  failing to validate XML when dw script is in a DWL file 

- mule-artifact-it/mule-deployer-it/pom.xml
- mule-artifact-it/mule-packager-it/pom.xml
- mule-artifact-it/pom.xml
- mule-classloader-model/pom.xml
- mule-deployer/pom.xml
- mule-extension-model-loader/pom.xml
- mule-maven-plugin/pom.xml
- mule-packager/pom.xml
- pom.xml
Updating version for the next circle.
> W-11127265 - Prepare for 2.6.2

- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/pom.xml
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/test/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployerTest.java
- mule-extension-model-loader/pom.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/internal/DefaultExtensionModelService.java
> CP: W-10915280, W-11025088

- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/simple-app-with-lib/src/main/mule/simple-app-with-lib.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-extension-model-loader/src/test/java/org/mule/tooling/internal/AstGeneratorTest.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/CompileMojo.java
we need to make jar dependencies accesible for the classrealm
> W-11221853:Application compile failing with MMP 3.6.x

- mule-artifact-it/mule-deployer-it/pom.xml
- mule-artifact-it/mule-packager-it/pom.xml
- mule-artifact-it/pom.xml
- mule-classloader-model/pom.xml
- mule-deployer/pom.xml
- mule-extension-model-loader/pom.xml
- mule-maven-plugin/pom.xml
- mule-packager/pom.xml
- pom.xml
> W-11308674: Preparing for the next cycle.

- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-extension-model-loader/src/test/java/org/mule/tooling/internal/ExtensionModelLoaderTest.java
(cherry picked from commit 091746e75f0863276031eddd8cbd8d79f0007ee6)
> W-11086385: Make `ArtifactPluginDescriptor` not extend `DeployableArtifactDescriptor` (#667)

- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/ProcessClassesMojoTest.java
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-structure-dependant-on-properties/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-structure-dependant-on-properties/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-structure-dependant-on-properties/src/main/mule/mule-application-structure-dependant-on-properties.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-unresolved-properties/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-unresolved-properties/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-unresolved-properties/src/main/mule/mule-application-with-unresolved-properties.xml
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstValidatonResult.java
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/DynamicStructureException.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
Also, add a waiver for validation on fields that have unresolved properties:
* W-11831692
* W-11802232
* W-11702416
> W-12143338: Properly identify import tag validation failures because of unresolved properties

- mule-artifact-it/mule-deployer-it/pom.xml
- mule-artifact-it/mule-packager-it/pom.xml
- mule-artifact-it/pom.xml
- mule-classloader-model/pom.xml
- mule-deployer/pom.xml
- mule-extension-model-loader/pom.xml
- mule-maven-plugin/pom.xml
- mule-packager/pom.xml
- pom.xml
> iW-12142665: Update Version For Next Release

- mule-packager/pom.xml
- pom.xml
**BUG:** [W-12591692](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001LmNO4YAN/view)
Adding missing dependency to avoid some warnings.
**BUG** [W-12593543](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001Ln8gTYAR/view)
Updating dependency to avoid a NoSuchMethodError exception
> [W-12591692] Adding missing dependency to avoid some warnings

- mule-extension-model-loader/pom.xml
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/AbstractMuleMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/utils/MuleApplicationModelLoader.java
- pom.xml
BUG: [W-12406825](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001Ji1qDYAR/view)
Error in MuleRuntime builds: Artifact required version is 4.6.0 and Mule Runtime version is 4.4.0
> [W-12406825] Error in MuleRuntime builds: Artifact required version is 4.6.0 and Mule Runtime version is 4.4.0

- mule-artifact-it/mule-packager-it/src/test/resources/custom-policy-test/src/main/mule/template.xml
- mule-deployer/pom.xml
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/test/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployerTest.java
- pom.xml
GUS Link: [W-12276532](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001IHlEBYA1/view
)
- If disableCloudHubLogsOption is set on the POM file this value should be the one set.
- Adding jersey-hk2 dependency, and fixing a test.
> W-12276532: if disableCloudHubLogsOption is set on POM file this value should be the one is set.

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
Temporary workaround until we update to the runtime version with the fix (4.5.0-rc9).
**This is an internal workaround, it should not be in the release notes.**
> W-12769196: MMP 3.8.4 - NullPointerException - When Error Handler hasn’t a Type

- mule-artifact-it/mule-deployer-it/pom.xml
- mule-artifact-it/mule-packager-it/pom.xml
- mule-artifact-it/pom.xml
- mule-classloader-model/pom.xml
- mule-deployer/pom.xml
- mule-extension-model-loader/pom.xml
- mule-maven-plugin/pom.xml
- mule-packager/pom.xml
- pom.xml
The release version was updated to 3.8.7-SNAPSHOT
- Task
> W 13830473: update release version to 3.8.7-SNAPSHOT

- mule-deployer/src/main/java/org/mule/tools/model/anypoint/RuntimeFabricDeploymentSettings.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/RuntimeFabricOnPremiseDeploymentSettings.java
> Feat(W-3942010): add status field and missing setter for persistent objectore, in RTF

- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/LifecyclePluginsGAVs.java
- pom.xml
[W-14278735] Update: exchange-mule-maven-plugin:0.0.23
[W-14125031] Upgrade Maven plugins bound to the MMP Lifecycle
> [W-14278735] Update: exchange-mule-maven-plugin:0.0.23

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/CloudHubDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/agent/ApplicationAgentDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/agent/DomainAgentDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/standalone/DomainStandaloneDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub-invalid-group-project/mule-artifact.json
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub-invalid-group-project/pom.xml
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub-invalid-group-project/src/main/mule/mule-config.xml
> [W-14274924] Run integration tests for MMP 4.0

- mule-extension-model-loader/pom.xml
- mule-packager/src/main/java/org/mule/tools/api/verifier/policy/PolicyYamlVerifier.java
- pom.xml
Fix New Vulnerabilities in mulesoft/mule-maven-plugin
- mule-deployer-it
- mule-maven-plugin
- mule-extension-model-loader
- mule-packager
- mule-deployer
> [W-14606100] Fix New Vulnerabilities in mulesoft/mule-maven-plugin

- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/InstallMojoTest.java
- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/ProcessClassesMojoTest.java
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file-invalid-path/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file-invalid-path/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file-invalid-path/src/main/mule/connectors/global-connectors.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file-invalid-path/src/main/mule/global.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file/mule-artifact.json
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file/pom.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file/src/main/mule/connectors/global-connectors.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file/src/main/mule/global.xml
- mule-artifact-it/mule-packager-it/src/test/resources/mule-application-with-import-file/src/main/resources/configurations/local-config.xml
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
> [W-14673992] Could not find imported resource during the MuleSoft build

- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/CloudHubDeployment.java
- mule-deployer/src/test/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployerTest.java
- mule-deployer/src/test/java/org/mule/tools/model/anypoint/CloudHubDeploymentTest.java
> [W-14653854] disableCloudhubLogs being overriden if not present in POM / Bug W-12276532 still present in mule maven plugin 4.0.0

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/CloudHubDeploymentTest.java
- mule-deployer/src/main/java/org/mule/tools/model/Deployment.java
- mule-deployer/src/main/java/org/mule/tools/model/anypoint/Cloudhub2Deployment.java
- mule-deployer/src/main/java/org/mule/tools/model/standalone/StandaloneDeployment.java
- mule-deployer/src/main/java/org/mule/tools/validation/AbstractDeploymentValidator.java
- mule-deployer/src/main/java/org/mule/tools/validation/EnvironmentSupportedVersions.java
> [W-14137714] Remove double validation in MMP

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/AbstractDeploymentTest.java
- mule-extension-model-loader/pom.xml
- pom.xml
**Issue:**
**Fix:**
**Tests:**
> [W-13104639] Updating mule-artifact-ast and fixing the IT

- mule-deployer/src/main/java/org/mule/tools/client/cloudhub/model/MuleVersion.java
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub/CloudHubArtifactDeployer.java
- mule-deployer/src/main/java/org/mule/tools/deployment/fabric/RequestBuilder.java
- mule-deployer/src/main/java/org/mule/tools/model/Deployment.java
> [W-14137736] Allow configuring JDK version in deployment config

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/CloudHubDeploymentTest.java
- mule-artifact-it/mule-deployer-it/wrapper.log
- mule-deployer/src/main/java/org/mule/tools/client/core/AbstractClient.java
- mule-deployer/src/test/java/org/mule/tools/client/core/AbstractClientTest.java
* W-15186546: JDK connector is not working with z/OS JVM
> W-15186546:JDK connector is not working with z/OS JVM (#817)

- mule-artifact-it/mule-deployer-it/pom.xml
- mule-artifact-it/mule-packager-it/pom.xml
- mule-artifact-it/pom.xml
- mule-classloader-model/pom.xml
- mule-deployer/pom.xml
- mule-extension-model-loader/pom.xml
- mule-maven-plugin/pom.xml
- mule-packager/pom.xml
- pom.xml
Upgrade to MMP 4.3.0-SNAPSHOT from main
> W-15903074: upgrade MMP version to 4.3.0-SNAPSHOT

- mule-deployer/src/main/java/org/mule/tools/client/core/AbstractClient.java
- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub2/RequestBuilderCh2.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/config/proxy/ProxyConfiguration.java
- pom.xml
**java 8 no proxy**
**java 11 no proxy**
**java 17 no proxy**
There is an issue with the http connector and java 17
[HTTP Patch with Jersey Client on JDK 16+](http://blog.supol.cz/?p=320)
**java 8 with proxy (invalid password)**
The default connector (JDK) does not take into account the proxy configuration
**java 11 with proxy (invalid password)**
**java 17 with proxy (invalid password)**
**java 8 with proxy (valid password)**
For the HTTP connector we have to verify that Basic authentication is allowed.
[Other Proxy-Related Properties](https://docs.oracle.com/en/java/javase/22/core/java-networking.html#GUID-801380C1-4300-4ED8-A390-3C39135267CD)
**java 11 with proxy (valid password)**
**java 17 with proxy (valid password)**
> [W-16046872] In MMP 4.x.x deploy command "mule:deploy" does not seem to take maven PROXY settings into account

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/Cloudhub2DeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-invalid-group-project/mule-artifact.json
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-invalid-group-project/pom.xml
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-invalid-group-project/src/main/mule/mule-config.xml
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-project/mule-artifact.json
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-project/pom.xml
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-project/src/main/mule/mule-config.xml
Deploy to CH2 Integration test added 
Integration test checked for Maven 3.9.4 and Java 8:
> W-16264008: Add 'Deploy to Cloudhub 2' Integration Test  

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/AbstractDeploymentTest.java
- pom.xml
Integration Tests Java 17 Maven 3.9.4
Integration Tests Java 11 Maven 3.8.8
Integration Tests Java 8 Maven 3.8.4
> W-16103007: Update Runtime Version to 4.7.2

- mmp-sonar/pom.xml
- mule-artifact-it/mule-deployer-it/pom.xml
- mule-artifact-it/mule-packager-it/pom.xml
- mule-artifact-it/pom.xml
- mule-classloader-model/pom.xml
- mule-deployer/pom.xml
- mule-extension-model-loader/pom.xml
- mule-maven-plugin/pom.xml
- mule-packager/pom.xml
- pom.xml
version to 4.4.0-SNAPSHOT after MMP 4.3.0-SNAPSHOT
> W-16585404: version to 4.4.0-SNAPSHOT

- mule-deployer/src/main/java/org/mule/tools/client/core/AbstractClient.java
https://github.com/user-attachments/assets/001502ff-f5d2-4204-a813-43f3f8c0747c
> [W-16911016] Fixing Apache5Connector issue

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/AbstractDeploymentTest.java
- pom.xml
> [W-16934473] Update Runtime Version to 4.7.4

- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/AbstractDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/CloudHubDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/Cloudhub2DeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/java/integration/test/mojo/Cloudhub2UBPDeploymentTest.java
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-UBP-invalid-group-project/mule-artifact.json
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-UBP-invalid-group-project/pom.xml
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-UBP-invalid-group-project/src/main/mule/mule-config.xml
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-UBP-project/mule-artifact.json
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-UBP-project/pom.xml
- mule-artifact-it/mule-deployer-it/src/test/resources/empty-mule-deploy-cloudhub2-UBP-project/src/main/mule/mule-config.xml
integration tests for MMP deploy to CH2 with UBP parameters
update deploy to CH2 and CH2 with runtime 4.8 
To use the new UBP required credentials in the Jenkins pipeline please approve this PR: https://github.com/mulesoft/lifecycle-pipeline-utils/pull/68
> W-16847178: integration tests for MMP deploy to CH2 with UBP parameters

- mule-deployer/src/main/java/org/mule/tools/deployment/cloudhub2/Cloudhub2ArtifactDeployer.java
- mule-deployer/src/main/java/org/mule/tools/deployment/fabric/RequestBuilder.java
- mule-deployer/src/main/java/org/mule/tools/deployment/fabric/RuntimeFabricArtifactDeployer.java
New logic to redeploy an app on CH2 or RTF
> [W-17013325] New logic to redeploy an app on CH2 or RTF

- pom.xml
[W-17348042](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000026FrKpYAK/view)
> [W-17348042] Leverage latest version of mule-maven-client (2.4.0-SNAPSHOT))

- Jenkinsfile
- build.jenkinsfile
- integrationTests-Windows.jenkinsfile
- integrationTests.jenkinsfile
- integrationTestsJDK11.jenkinsfile
> W-17368254: update to from lifecycle-utils master to main  branch

- mule-deployer/src/test/java/org/mule/tools/client/standalone/controller/probing/DeploymentProbeFactoryTest.java
- mule-deployer/src/test/java/org/mule/tools/client/standalone/controller/probing/deployment/ApplicationDeploymentProbeTest.java
- mule-deployer/src/test/java/org/mule/tools/client/standalone/controller/probing/deployment/DomainDeploymentProbeTest.java
Tests added for org.mule.tools.client.standalone.controller.probing.deployment
> W-17506523: MORATORIUM - increase MMP coverage

- mule-artifact-it/mule-packager-it/src/test/java/integration/test/mojo/PackageMojoTest.java
- mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
- mule-extension-model-loader/src/main/java/org/mule/tooling/internal/DefaultExtensionModelService.java
- mule-extension-model-loader/src/main/java/org/mule/tooling/internal/PluginResources.java
- mule-extension-model-loader/src/test/java/org/mule/tooling/internal/DefaultExtensionModelServiceTest.java
- mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/ProcessClassesMojo.java
- mule-maven-plugin/src/test/java/org/mule/tools/maven/mojo/ProcessClassesMojoTest.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/DefaultValuesMuleArtifactJsonGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/packager/sources/MuleContentGenerator.java
- mule-packager/src/main/java/org/mule/tools/api/packager/structure/ProjectStructure.java
- mule-packager/src/test/java/org/mule/tools/api/packager/sources/DefaultValuesMuleArtifactJsonGeneratorTest.java
During the process classes phase the custom dependencies are being read and the dwl resources are stored in a file in the target.
During the generate resources phase the aux file will be read and added to the generated mule-artifact.json
> W-17578789: exporting dwl files

- mule-classloader-model/pom.xml
- mule-classloader-model/src/main/java/org/mule/tools/api/classloader/model/AppClassLoaderModel.java
- mule-classloader-model/src/main/java/org/mule/tools/api/classloader/model/ClassLoaderModel.java
* Piggyback: add automatic module name
> W-18697796: Avoid GSON from using `jdk.unsupported` module
